<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ocean</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>^\s*\}</string>
	<key>name</key>
	<string>OceanScript</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>@[_a-zA-Z][_a-zA-Z0-9]*\b</string>
			<key>name</key>
			<string>variable.oceanscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\?[_a-zA-Z][_a-zA-Z0-9]*\b</string>
			<key>name</key>
			<string>variable.parameter.oceanscript</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.oceanscript</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.oceanscript</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.oceanscript</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#interpolated</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>interpolated</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>@[_a-zA-Z][_a-zA-Z0-9]*\b</string>
					<key>name</key>
					<string>variable</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>@\(</string>
					<key>end</key>
					<string>\)</string>
					<key>name</key>
					<string>string.interpolation</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.oceanscript</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.oceanscript</string>
	<key>uuid</key>
	<string>680491D0-A323-4442-8262-AB07B93CC386</string>
</dict>
</plist>
