#!/usr/bin/env node

var argv = require('optimist')
    .boolean('c').alias('c', 'compile')
    .boolean('u').alias('u', 'ugly')
    .argv;
    
var commandLine = require('./commandLine');

if (argv.compile) {
  for (var i in argv._) {
    commandLine.compileFile(argv._[i], {ugly: argv.ugly});
  }
} else {
  commandLine.runFile(argv._[0]);
}