#!/usr/bin/env node --prof --prof_browser_mode

var argv = require('optimist').boolean('c').alias('c', 'compile').argv;
var commandLine = require('./commandLine');

if (argv.c) {
  for (var i in argv._) {
    commandLine.compileFile(argv._[i]);
  }
} else {
  commandLine.runFile(argv._[0]);
}